# Site settings 사이트 구성
title: 'your awesome title'
description: 'your web description'
keywords: 'your web keywords, another keywords'
url: 'https://JJunghyunY.github.io' # your host

# nav 공간：&emsp;
nav: # 6개의 태그를 가장 잘 경험하고 태그당 4자 이하 사용하는 것이 좋습니다.
  Home: '/'
  Tags: '/tags.html'
  Timeline: '/timeline.html'
  About: '/about.html'
  FriendLink: '/friendLink.html'

# 블로거
author: true
name: 'Junghyun Yoo'
NickName: 'junyoo'
webtitle: 'your awesome webtitle'
bio: 'bio'
about: true
aboutyou: 'logging about swift'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: false
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:abc@gmail.com'
  weixin: ''
  qq: ''
  github: ''
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

# 쪽수
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2022

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# highlighter rouge
highlighter: rouge
# 코드 강조 테마는 pygments 테마를 사용합니다. autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 원하는 테마 이름을 선택하고 아래 작은 따옴표를 입력하십시오.
pygmentsTheme: 'default'

# 연결
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 댓글 최고의 경험 disqus, livere 및 Gitment 중에서 선택
# disqus 논평
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 빌리 댓글로 오세요
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment논평 OAuth Application
Gitment: false
Gitment_owner: '' # github 사용자 이름
Gitment_repo: '' # github 블로그가 저장된 저장소 이름
client_id: '' # OAuth 애플리케이션 등록 후 얻은 client_id
client_secret: '' # OAuth 애플리케이션 등록 후 얻은 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: false
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# Baidu Statistics baidu-url에 자신의 URL 코드 입력
baidu: false
baidu-url: ''
# Google Analytics google-ID에 Google Analytics에서 얻은 추적 ID를 입력
google: false
google-ID: ''

# 블로그 헤더 정보 대체 색상 (이 부분은 사이트에서 사이트 변수 역할을 하지 않으며, 페이지 변수 역할을 하도록 포스트 헤더 정보에 작성)
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
